# Generated by Django 2.2.7 on 2019-11-18 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('genus', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=150)),
                ('colors', models.CharField(max_length=150)),
                ('com_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
                ('distribution', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
            ],
        ),
    ]
