# Generated by Django 2.2.7 on 2019-11-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='com_names',
        ),
        migrations.RemoveField(
            model_name='species',
            name='distribution',
        ),
        migrations.CreateModel(
            name='Dist_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_point', to='BugBytes.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Com_Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_name', to='BugBytes.Species')),
            ],
        ),
    ]
