# Generated by Django 2.2.7 on 2019-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0002_auto_20191118_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
