# Generated by Django 2.2.7 on 2019-11-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0003_species_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dist_Point',
        ),
    ]
