# Generated by Django 2.2.7 on 2019-11-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0004_delete_dist_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='avatar',
        ),
        migrations.AddField(
            model_name='species',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='BugBytes.Species')),
            ],
        ),
    ]
