# Generated by Django 2.2.7 on 2019-11-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0005_auto_20191120_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_names',
            old_name='names',
            new_name='name',
        ),
    ]
