# Generated by Django 2.2.7 on 2019-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugBytes', '0007_test_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Image',
        ),
    ]
